ConsultarEndereçoAPI/ConsultarEndereçoAPI/Models/Contexto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConsultarEndereçoAPI.Models;
using Microsoft.EntityFrameworkCore;

namespace ConsultarEndereçoAPI.Models
{
    public class Contexto : DbContext
    {
        public DbSet<Endereco> Enderecos { get; set; }
        public Contexto(DbContextOptions<Contexto> options) : base(options)
        {
        }   
    }
}

ConsultarEndereçoAPI/ConsultarEndereçoAPI/Models/Endereco.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ConsultarEndereçoAPI.Models
{
    [Table("Enderecos")]
    public class Endereco
    {
        [Key]
        public int enderecoId { get; set; }
        public string cep  { get; set; }
        public string logradouro { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string localidade { get; set; }
        public string uf { get; set; }
    }
}

ConsultarEndereçoAPI/ConsultarEndereçoAPI/Controllers/EnderecoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using ConsultarEndereçoAPI.Dal;
using ConsultarEndereçoAPI.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

// Ariane Noirine Pimentel Silva Assis Neves, Matricula 1621586

namespace ConsultarEndereçoAPI.Controllers
{
    public class EnderecoController : Controller
    {

        private readonly EnderecoDAO _enderecoDAO;
        public EnderecoController(EnderecoDAO enderecoDAO)
        {
            _enderecoDAO = enderecoDAO;
            
        }        
      
        public IActionResult Inicial()
        {
            
            if (TempData["resultado"] != null)
            {
                string resultado = TempData["resultado"].ToString();
                Endereco endereco = JsonConvert.DeserializeObject<Endereco>(resultado);

                    _enderecoDAO.Cadastrar(endereco);
                    return View(_enderecoDAO.Listar());              

            }
            return View(_enderecoDAO.Listar());            
        }       

        [HttpPost]
        public IActionResult ConsultaCep (string cep) 
        {         
                string url = $@"http://viacep.com.br/ws/{cep}/json/";
                WebClient endereco = new WebClient();
                TempData["resultado"] = endereco.DownloadString(url);
                      
                return RedirectToAction("Inicial");           
                        
        }

        public ActionResult Remover(int id)
        {
            _enderecoDAO.Remover(id);

            return RedirectToAction("Inicial");
        }

        public IActionResult Alterar(int id)
        {

            Endereco endereco = _enderecoDAO.ReceberDado(id);
            return View(endereco);
        }

        [HttpPost]
        public IActionResult Alterar(Endereco endereco)
        {
            _enderecoDAO.Alterar(endereco);
            return RedirectToAction("Inicial");
        }

    }
}

ConsultarEndereçoAPI/ConsultarEndereçoAPI/Controllers/EnderecosAPIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConsultarEndereçoAPI.Dal;
using ConsultarEndereçoAPI.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

// Ariane Noirine Pimentel Silva Assis Neves, Matricula 1621586

namespace ConsultarEndereçoAPI.Controllers
{
    [Route("api/Endereco")]
    [ApiController]
    public class EnderecosAPIController : ControllerBase
    {
        private readonly EnderecoDAO _enderecoDAO;
        public EnderecosAPIController(EnderecoDAO enderecoDAO)
        {
            _enderecoDAO = enderecoDAO;

        }
        //GET: /api/Endereco/ListarEnderecos
        [HttpGet]
        [Route("ListarEnderecos")]
        public IActionResult ListarEnderecos()
        {
            return Ok (_enderecoDAO.Listar());
        }

        //GET: /api/Endereco/ListarEndereco/81730000
        [HttpGet]
        [Route("ListarEndereco")]
        public IActionResult ListarEndereco(int cep)
        {
            Endereco endereco = _enderecoDAO.BuscarEndereco(cep);
            return Ok (endereco);
        }

        //POST: /api/Endereco/CadastrarEndereco
        [HttpPost]
        [Route("CadastrarEndereco")]
        public IActionResult CadastrarEndereco(Endereco endereco)
        {
            _enderecoDAO.Cadastrar(endereco);
            return Created("", endereco);
        }

        //PUT: /api/Endereco/AlterarEndereco
        [HttpPut]
        [Route("AlterarEndereco")]
        public IActionResult AlterarEndereco(int id)
        {
            Endereco endereco = _enderecoDAO.ReceberDado(id);
            _enderecoDAO.Alterar(endereco);
            return Created("", endereco);
        }

        //DELETE: /api/Endereco/DeletarEndereco/2
        [HttpDelete]
        [Route("DeletarEndereco")]
        public IActionResult DeletarEndereco(int id)
        {
            _enderecoDAO.Remover(id);
            return Ok ();
        }
    }
}

ConsultarEndereçoAPI/ConsultarEndereçoAPI/Views/Endereco/Alterar.cshtml
@model Endereco
    <!--Ariane Noirine Pimentel Silva Assis Neves, Matricula 1621586-->

    <!DOCTYPE html>

    <html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>Inserir Complemento</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body class="container" style="padding-top:30px">

        <form asp-action="Alterar" asp-controller="Endereco" class="col-6 ">
            <fieldset>
                <legend>Inserir Complemento</legend>

                <div class="form-group">
                    <input type="hidden" asp-for="enderecoId" />
                </div>

                <div class="form-group">
                    <input type="hidden" asp-for="cep" class="form-control" required="required" />
                </div>

                <div class="form-group">

                    <input type="hidden" asp-for="logradouro" class="form-control" required="required" />
                </div>

                <div class="form-group">
                    <label asp-for="complemento">Complemento:</label>
                    <input type="text" asp-for="complemento" class="form-control" />
                </div>

                <div class="form-group">

                    <input type="hidden" asp-for="bairro" class="form-control" required="required" />
                </div>

                <div class="form-group">

                    <input type="hidden" asp-for="localidade" class="form-control" required="required" />
                </div>

                <div class="form-group">

                    <input type="hidden" asp-for="uf" class="form-control" required="required" />
                </div>


                <input type="submit" value="Alterar" class="btn btn-success" asp-for="enderecoId" />

            </fieldset>
        </form>

    </body>
</html>

ConsultarEndereçoAPI/ConsultarEndereçoAPI/Views/Endereco/Erro.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Erro</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body class="container" style="padding-top:50px">
    <fieldset>
        <legend>Erro.</legend>
        <a>Ocorreu um erro ao processar sua solicitação. O CEP informado já está cadastrado ou não existe.</a>
    </fieldset>
</body>
</html>

ConsultarEndereçoAPI/ConsultarEndereçoAPI/Views/Endereco/Inicial.cshtml
@model List<Endereco>


<!--Ariane Noirine Pimentel Silva Assis Neves, Matricula 1621586-->

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title> Consulta e Cadastro de CEP</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body class="container" style="padding-top:40px">

    <fieldset>
        <legend>Consulta e Cadastro de CEP</legend>

            <nav class="navbar navbar-light bg-light">
                <form class="form-inline" asp-action="ConsultaCep" asp-controller="Endereco">
                    <input type="text" class="form-control mr-sm-2" id="cep" name="cep" placeholder="Informe o CEP" aria-label="Search" required="required">
                    <input type="submit" value="Consultar e Cadastrar" class="btn btn-outline-success my-2 my-sm-0"/>
                </form>
            </nav>
       
        <br> <br>

        <table class="table table-hover">
            <thead class="p-3 mb-2 bg-success text-white">
                <tr>
                    <th scope="col">Cód.</th>
                    <th scope="col">CEP</th>
                    <th scope="col">Logradouro</th>
                    <th scope="col">Complemento</th>
                    <th scope="col">Bairro</th>
                    <th scope="col">Localidade</th>
                    <th scope="col">Estado</th>
                    <th scope="col">
                        <svg width="8em" height="1em" viewBox="0 0 16 16" class="bi bi-house-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M8 3.293l6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z" />
                            <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z" />
                        </svg>
                    </th>
                </tr>
            </thead>
            @foreach (Endereco u in Model)
            {
                <tr>
                    <td>@u.enderecoId</td>
                    <td>@u.cep</td>
                    <td>@u.logradouro</td>
                    <td>@u.complemento</td>
                    <td>@u.bairro</td>
                    <td>@u.localidade</td>
                    <td>@u.uf</td>

                    <td>
                        <a class="font-italic" asp-action="Alterar" asp-controller="Endereco" asp-route-id="@u.enderecoId">Alterar / </a>
                        <a class="font-italic" asp-action="Remover" asp-controller="Endereco" asp-route-id="@u.enderecoId">Remover</a>

                    </td>
                </tr>
            }
        </table>

    </fieldset>
</body>
</html>